version: '3.7'
services:
    traefik:
        image: traefik:latest
        container_name: traefik
        command:
            - "--api.dashboard=true"
            - "--api.insecure=true"
            - "--providers.docker"
            - "--accesslog.filepath=/data/access.log"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.traefik.address=:8080"
        ports:
            - "80:80"
            - "3306:3306"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        networks:
            - connector
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./src/${PROJECT_DIR}:/var/www/html"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`app.localhost`)"
            - "traefik.port=80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: unless-stopped
        depends_on:
            - php
        networks:
            - connector
    php:
        image: php${PHP_VERSION}
        container_name: php
        restart: unless-stopped
        build:
            ssh:
                - default
            context: etc/php/${PHP_VERSION}
            dockerfile: Dockerfile
        environment:
            - PHP_IDE_CONFIG=serverName=PHPSTORM
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./src/${PROJECT_DIR}:/var/www/html"
            - "./ssh:/var/www/html/.ssh:ro"
        networks:
            - connector
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: unless-stopped
        labels:
            - "traefik.http.routers.myadmin.rule=Host(`myadmin.localhost`)"
        depends_on:
            - traefik
            - mysqldb
        networks:
            - connector
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - connector
    mailer:
        image: axllent/mailpit
        container_name: mailer
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mailer.rule=Host(`mail.localhost`)"
            - "traefik.http.services.mailer.loadbalancer.server.port=8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - connector
networks:
    connector:
        driver: bridge
volumes:
    dbdata:

