version: '3.7'
services:
    traefik:
        image: traefik:latest
        container_name: traefik
        command:
            - "--api.dashboard=true"
            - "--api.insecure=true"
            - "--providers.docker"
            - "--accesslog.filepath=/data/access.log"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.traefik.address=:8080"
        ports:
            - "80:80"
            - "3306:3306"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        networks:
            - connector
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - "./etc/nginx/conf.d:/etc/nginx/conf.d/"
            - "./src:/var/www/html"
        extends:
            file: ./etc/nginx/domains.yaml
            service: domains
        labels:
            - "traefik.enable=true"
            - "traefik.port=80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: unless-stopped
        command: [nginx-debug, '-g', 'daemon off;']
        networks:
            - connector
    php82:
        image: php82
        container_name: php82
        restart: unless-stopped
        extends:
            file: ./etc/projects/php82.yaml
            service: php82-projects
        build:
            ssh:
                - default
            dockerfile: etc/php/82/Dockerfile
        environment:
            - PHP_IDE_CONFIG=serverName=PHPSTORM
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./ssh:/home/docker/.ssh:ro"
        networks:
            - connector
    php80:
        image: php80
        container_name: php80
        restart: unless-stopped
        extends:
            file: ./etc/projects/php80.yaml
            service: php80-projects
        build:
            ssh:
                - default
            dockerfile: etc/php/80/Dockerfile
        environment:
            - PHP_IDE_CONFIG=serverName=PHPSTORM
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./ssh:/home/docker/.ssh:ro"
        networks:
            - connector
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - UPLOAD_LIMIT=16G
            - PMA_HOSTS=${MYSQL_HOST}, ${MYSQL_HOST_1}
        restart: unless-stopped
        labels:
            - "traefik.http.routers.myadmin.rule=Host(`myadmin.localhost`)"
        depends_on:
            - traefik
            - mysqldb
            - mysqldb1
        networks:
            - connector
    mailer:
        image: axllent/mailpit
        container_name: mailer
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mailer.rule=Host(`mail.localhost`)"
            - "traefik.http.services.mailer.loadbalancer.server.port=8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - connector
networks:
    connector:
        driver: bridge

